# hosts-definition.yml
#
# Galaxy production infrastructure 
#

---
default_volumes:
 - device_name: /dev/sda1
   volume_type: gp2
   volume_size: 8 
   delete_on_termination: yes 

galaxy_hosts:

# master database
- count: 1
  type: m3.large
  subnet: "{{ galaxy_subnets[0] }}"
  volumes:
    - device_name: /dev/sda1
      volume_type: io1 
      volume_size: 36 
      iops: 1800
      delete_on_termination: no
  tags:
    Name: galaxy-pr-db-01
    galaxy: prod
    galaxy_group: pr_db
    galaxy_postgres: master

# replication database
- count: 1
  type: m3.large
  subnet: "{{ galaxy_subnets[1] }}"
  volumes:
    - device_name: /dev/sda1
      volume_type: io1
      volume_size: 36
      iops: 1800
      delete_on_termination: no 
  tags:
    Name: galaxy-pr-db-02
    galaxy: prod
    galaxy_group: pr_db
    galaxy_postgres: slave

# elasticsearch hosts
- count: 1
  type: t2.medium
  volumes: "{{ default_volumes }}"
  subnet: "{{ galaxy_subnets[0] }}"
  tags:
    Name: galaxy-pr-es-01
    galaxy: prod
    galaxy_group: pr_elastic 

- count: 1
  type: t2.medium
  subnet: "{{ galaxy_subnets[1] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-es-02
    galaxy: prod
    galaxy_group: pr_elastic 

- count: 1
  type: t2.medium
  subnet: "{{ galaxy_subnets[1] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-es-03
    galaxy: prod
    galaxy_group: pr_elastic 
      
# web hosts
- count: 1
  type: t2.medium
  subnet: "{{ galaxy_subnets[0] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-web-01
    galaxy: prod
    galaxy_group: pr_web 

- count: 1
  type: t2.medium
  subnet: "{{ galaxy_subnets[1] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-web-02
    galaxy: prod
    galaxy_group: pr_web 

# celery host
- count: 1
  type: t2.small
  subnet: "{{ galaxy_subnets[0] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-celery-01
    galaxy: prod
    galaxy_group: pr_celery
    galaxy_celery_queue: imports

# celery host
- count: 1
  type: t2.small
  subnet: "{{ galaxy_subnets[1] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-celery-02
    galaxy: prod
    galaxy_group: pr_celery
    galaxy_celery_queue: user

# celery host
- count: 1
  type: t2.small
  subnet: "{{ galaxy_subnets[1] }}"
  volumes: "{{ default_volumes }}"
  tags:
    Name: galaxy-pr-celery-03
    galaxy: prod
    galaxy_group: pr_celery
    galaxy_celery_queue: admin
