language: python
dist: trusty
sudo: required
services:
- docker

before_install:
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq

install:
- pip install ansible flake8

script:
# run flake8
- make test/flake8

# build images
- make dev/build

# start the application
- make dev/up_detached
- make dev/waitenv
- make dev/test

# check images running
- docker ps -a
- docker images

# Run simple web server test
- pushd testing/simple
- ansible-playbook -i inventory test.yml
- popd

# Stop the application
- make dev/down
