---
# AWS variables
aws_url: 'https://ec2.amazonaws.com'
aws_access_key: ''
aws_secret_key: ''
ec2_region: 'us-east-1'
ec2_instance_type: 'm3.medium'
ec2_key_name: 'galaxy-testing'
ec2_public_key: '~/.ssh/id_rsa.pub'
ec2_name_prefix: 'galaxy-testing'
ec2_security_group: 'Galaxy'

# default list of images
ec2_images:
  - name: ami-96a818fe
    description: centos-7.0-x86_64

# list of required security groups
ec2_security_groups:
  - name: Galaxy
    description: Galaxy Security Group
    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 443
      to_port: 443
      cidr_ip: 0.0.0.0/0
