---
- name: Install Elasticsearch
  hosts: all
  sudo: yes
  roles:
    - { role: sysctl }
    - { role: packages }
    - { role: geerlingguy.elasticsearch }
    - { role: elasticsearch_config }
    - { role: ntp }
    - { role: iptables }
    - { role: fail2ban }
    - { role: auth_users }
    - { role: auth_keys }
