- name: Nopasswd sudoer access
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: Set the hostname
  hostname: name="{{ host_name }}"

- name: Disable ssh root login
  lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^#PermitRootLogin yes'
      line: 'PermitRootLogin no'
  notify:
      - restart_ssh
