---

- name: install epel
  yum: name=epel-release

- name: install RPM packages required for galaxy
  yum: name={{item}}
  with_items:
  - gcc
  - git
  - httpd
  - iptables-services
  - libjpeg
  - libselinux-python
  - libsemanage-python
  - make
  - memcached
  - mod_wsgi
  - mod_ssl
  - python-devel
  - python-pip
  - python-psycopg2
  - python-setuptools
  - PyYAML
  - python-memcached
  - rabbitmq-server
  - supervisor
  - tmux
  - zlib

- name: install development tool packages
  yum: name={{item}}
  with_items:
  - npm
  when: galaxy_install_dev_tools

- name: install pip packages required for galaxy
  pip: name=django version=1.8.3

- name: install pip packages required for galaxy
  pip: name={{item}}
  with_items:
  - decorator
  - django-allauth
  - django-autofixture
  - django-avatar
  - django-bootstrap-form
  - django-celery
  - django-filter
  - django-site-maintenance
  - djangorestframework==2.4.6
  - django-debug-toolbar
  - markdown==2.4.1 # 2.5 currently has a python 2.6.x incompatibility
  - PyGithub
  - requests
  - requests-oauthlib

# the avatars directory needs to be there, otherwise the library
# will complain. It isn't used, as all the avatar info is stored
# in the database

- name: configure django-avatars directory
  file: path=/var/www/avatars state=directory mode=0755 owner=apache group=apache

- name: create galaxy_manage group
  group: name=galaxy_manage state=present

- name: add vagrant to galaxy_manage group
  user: name=vagrant append=yes groups=galaxy_manage
  when: galaxy_env == "DEV"

- name: add centos to galaxy_manage group
  user: name=centos append=yes groups=galaxy_manage
  when: galaxy_env == "PROD"

- name: add apache to galaxy_manage group
  user: name=apache append=yes groups=galaxy_manage
  when: galaxy_env == "PROD"

# semanage fcontext -a -t httpd_log_t "/var/log/galaxy(/.*)?"
# restorecon -R -v /var/log/galaxy

- name: configure galaxy log directory
  file:
      path: "{{ galaxy_log_dir }}"
      state: directory
      owner: root
      group: galaxy_manage
      mode: 2770
      recurse: yes
      seuser: system_u
      serole: object_r
      setype: httpd_log_t
  when: galaxy_env == "PROD"
