---

- name: create the galaxy group for the galaxy user
  group: name=galaxy system=yes

- name: create the galaxy user for celery
  user: name=galaxy group=galaxy groups=apache,galaxy_manage system=yes createhome=no shell=/sbin/nologin

- name: Add Galaxy Config to supervisord.conf with Beats
  ini_file: dest={{sup_conf_location}} section="program:galaxy-celeryd" option="{{item.option}}" value="{{item.value}}"
  with_items:
    - option: command
      value: "/usr/bin/galaxy-manage celeryd -B -l info -Q {{ celery_queues }} --autoscale={{ celery_autoscale }}"
    - option: directory
      value: "/var/lib/galaxy"
    - option: user
      value: "galaxy"
    - option: autostart
      value: "true"
    - option: autorestart
      value: "true"
    - option: stopwaitsecs
      value: 600
    - option: log_stdout
      value: "true"
    - option: log_stderr
      value: "true"
    - option: stdout_logfile
      value: "/var/log/galaxy/celeryd.log"
    - option: stderr_logfile
      value: "/var/log/galaxy/celeryd.log"
    - option: logfile_maxbytes
      value: 50MB
    - option: logfile_backups
      value: 999
  when: celery_beats
  notify: restart supervisor
  tags: supervisor

- name: Add Galaxy Config to supervisord.conf without Beats
  ini_file: dest={{sup_conf_location}} section="program:galaxy-celeryd" option="{{item.option}}" value="{{item.value}}"
  with_items:
    - option: command
      value: "/usr/bin/galaxy-manage celeryd -l info -Q {{ celery_queues }} --autoscale={{ celery_autoscale }}"
    - option: directory
      value: "/var/lib/galaxy"
    - option: user
      value: "galaxy"
    - option: autostart
      value: "true"
    - option: autorestart
      value: "true"
    - option: stopwaitsecs
      value: 600
    - option: log_stdout
      value: "true"
    - option: log_stderr
      value: "true"
    - option: stdout_logfile
      value: "/var/log/galaxy/celeryd.log"
    - option: stderr_logfile
      value: "/var/log/galaxy/celeryd.log"
    - option: logfile_maxbytes
      value: 50MB
    - option: logfile_backups
      value: 999
  when: not celery_beats
  notify: restart supervisor
  tags: supervisor
