- name: Restart supervisord
  service: name=supervisord state=restarted enabled=yes
  tags:
      - celery

- name: Restart rabbitmq
  service: name=rabbitmq-server state=restarted enabled=yes
  tags:
      - celery
