---
- name: Check for the tar file
  shell: ls -1 {{ galaxy_dist_dir }}/galaxy-*.tar.gz
  register: app_tar
  tags:
    - web
    - celery 

- name: Remove the existing app
  pip: name=galaxy state=absent
  ignore_errors: yes
  tags:
    - web
    - celery 

- name: Install the Galaxy app
  pip: name={{ app_tar.stdout }}
  tags:
    - web
    - celery 


- name: Configure /etc/galaxy directory
  file: path=/etc/galaxy owner=root group=galaxy_manage mode=2770 state=directory
  tags:
    - web
    - celery 

- name: Deploy settings file
  template: src=settings.py.j2 dest=/etc/galaxy/settings.py owner=root group=galaxy_manage mode=0660
  tags:
    - web
    - celery 

- name: Create the SECRET_KEY file
  command: /usr/bin/python -c "import uuid; file('/etc/galaxy/SECRET_KEY', 'wb').write(uuid.uuid4().hex)" creates=/etc/galaxy/SECRET_KEY
  tags:
    - web
    - celery 

- name: Adjust SECRET_KEY permissions
  file: path=/etc/galaxy/SECRET_KEY state=file owner=root group=galaxy_manage mode=0660
  tags:
    - web
    - celery 

- name: Celery tasks
  inlcude: celery.yml
  when: galaxy_deploy_celery

- name: Web tasks
  include: web.yml
  when: galaxy_deploy_web
