---
- name: Check for the tar file
  shell: ls -1 {{ galaxy_dist_dir }}/*.tar.gz
  register: app_tar

- name: Install the Galaxy app
  pip: name={{ app_tar.stdout }}

- name: Make migrations
  command: galaxy-manage makemigrations --noinput

- name: Apply migrations
  command: galaxy-manage migrate --noinput

- name: Collect galaxy static files
  command: galaxy-manage collectstatic --clear --noinput
