- name: Configure galaxy/public/static directory
  file: path=/var/lib/galaxy/public/static state=directory mode=0755
  tags:
    - web

- name: Deploy apache configuration file
  template: src=galaxy.conf.j2 dest=/etc/httpd/conf.d/galaxy.conf
  tags:
    - web

- name: Apply migrations
  command: galaxy-manage migrate --fake-initial --noinput
  when: django_migrate
  tags:
    - web

- name: Collect galaxy static files
  command: galaxy-manage collectstatic --clear --noinput
  tags:
    - web
  notify:
    - restart apache

- name: Rebuild Search Indexes
  shell: "galaxy-manage rebuild_index --noinput"
  when: es_rebuild_host

- name: Rebuild custom search indexes
  shell: "galaxy-manage rebuild_galaxy_indexes"
  when: es_rebuild_host
