# tasks/main.yml
---

- name: Remove old wheel files
  file:
    path: '{{ item }}'
    state: absent
  with_fileglob:
  - '/tmp/galaxy-*-none-any.whl'

- name: Copy the file
  copy:
    src: "{{ galaxy_dist_file }}"
    dest: "/tmp/{{ galaxy_dist_file | basename }}"

- name: Stat the wheel file
  stat:
    path: "/tmp/{{ galaxy_dist_file | basename }}"
  register: stat_output

- name: Show wheel file status
  debug: var=stat_output

