version: '3'

services:
  galaxy:
    image: galaxy-dev:latest
    build:
      context: ./docker-dev
    volumes:
      - ${PWD}:/galaxy:rw
    environment:
      - TMUX
    ports:
      - '8000:8000'
    links:
      - postgres
      - elastic
      - memcache
      - rabbitmq

  postgres:
    image: centos/postgresql-95-centos7 
    environment:
      - POSTGRESQL_DATABASE=galaxy
      - POSTGRESQL_USER=galaxy
      - POSTGRESQL_PASSWORD=galaxy

  elastic:
    image: 'ansible/galaxy-elasticsearch:2.4.6'

  memcache:
    image: memcached:latest

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=galaxy
      - RABBITMQ_DEFAULT_PASS=galaxy
      - RABBITMQ_DEFAULT_VHOST=galaxy
