---
# copy the distribution tar file to the remote hosts

- name: Get the name of the local distribution file
  hosts: 127.0.0.1 
  connection: local
  tasks:
    - shell: ls -1 $(pwd)/dist/galaxy-*.tar.gz chdir="{{ playbook_dir }}/.."
      register: app_tar

- name: Copy the distribution file to web and celery hosts 
  hosts: web, celery 
  tasks:
    - name: Remove old dist files
      shell: rm -f /tmp/galaxy-*.tar.gz
    - name: Copy the file
      copy: src={{ hostvars['127.0.0.1']['app_tar'].stdout }} dest=/tmp/{{ hostvars['127.0.0.1']['app_tar'].stdout | basename }}
      register: copy_result
