---
# copy the distribution tar file to the remote hosts

- name: copy the distribution tar file to the remote hosts 
  hosts: local
  tasks:
    - shell: ls -1 $(pwd)/dist/*.tar.gz chdir="{{ playbook_dir }}/.."
      register: app_tar

- name: copy the dist file
  hosts: ec2 
  tasks:
    - copy: src={{ hostvars['local']['app_tar.stdout'] }} dest=/tmp/{{ hostvars['local'][app_tar.stdout] | basename }}
      register: copy_result

- name: add galaxy_dist_file variable
  hosts: local
  tasks:
    - shell: echo "galaxy_dist_file\0072 {{ copy_result.dest }}" >>{{ playbook_dir }}/vars.yml
      when: copy_result is defined
