- name: Deploy Galaxy
  hosts: all
  sudo: yes
  vars:
      galaxy_github_api_token: "{{ lookup('env', 'GALAXY_GITHUB_API_TOKEN') }}"
      galaxy_email_username: "{{ lookup('env', 'GALAXY_EMAIL_USERNAME') }}"
      galaxy_email_password: "{{ lookup('env', 'GALAXY_EMAIL_PASSWORD' )}}"
      galaxy_rabbit_password: "{{ lookup('env', 'GALAXY_RABBIT_PASSWORD' )}}"
      galaxy_rabbit_hostname: "{{ lookup('env', 'GALAXY_DATABASE_HOST' ) | default('127.0.0.1', true) }}"
      galaxy_postgresql_hostname: "{{ lookup('env', 'GALAXY_DATABASE_HOST' ) | default('127.0.0.1', true) }}"
      galaxy_postgresql_password: "{{ lookup('env', 'GALAXY_POSTGRESQL_PASSWORD') | default('galaxy',true) }}"
      galaxy_memcached_hostname: "{{ lookup('env', 'GALAXY_DATABASE_HOST' ) | default('127.0.0.1', true) }}"
  roles:
  - { role: galaxy_deploy }
