---

- name: Deploy Web Servers
  hosts: web
  become: yes
  vars:
      - galaxy_database_local: no
      - galaxy_deploy_web: yes
      - galaxy_deploy_celery: no
  vars_files:
      - galaxy-vault.yml
  roles:
      - { role: galaxy_packages }
      - { role: galaxy_deploy }

- name: Deploy Celery
  hosts: celery 
  become: yes
  vars:
      - galaxy_database_local: yes
      - galaxy_deploy_web: no 
      - galaxy_deploy_celery: yes 
  vars_files:
      - galaxy-vault.yml
  roles:
      - { role: galaxy_packages }
      - { role: galaxy_deploy }

- name: Notify slack
  hosts: 127.0.0.1 
  connection: local
  vars:
      slack_message: "{{ galaxy_slack_message | default('None') }}"
  roles:
      - { role: notify_slack,
          notify_slack_message: "{{ slack_message }}",
          when: slack_message != 'None' }
