---

- name: Include vars
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Include vars
      include_vars: galaxy-vault.yml

- name: Deploy Web Servers
  hosts: web
  sudo: yes
  roles:
  - { role: galaxy_packages }
  - { role: galaxy_deploy , tags: ["all", "web"] }
  # - { role: notify_slack, notify_slack_message: "{{ galaxy_slack_message }}", when: galaxy_slack_message is defined }

- name: Deploy Celery
  hosts: celery
  sudo: yes
  roles:
  - { role: galaxy_packages }
  - { role: galaxy_deploy , tags: ["all", "celery"] }

- name: Rebuild Search Indexes
  hosts: es_rebuild_host
  tasks:
    - shell: "echo 'y' | galaxy-manage rebuild_index"

- name: Rebuild custom search indexes
  hosts: es_rebuild_host
  tasks:
    - shell: "galaxy-manage rebuild_galaxy_indexes"
