- name: Deploy Galaxy
  hosts: all
  sudo: yes
  vars:
      galaxy_postgresql_password: "{{ lookup('env', 'GALAXY_POSTGRESQL_PASSWORD') | default('galaxy',true) }}"
      galaxy_github_api_token: "{{ lookup('env', 'GALAXY_GITHUB_API_TOKEN') }}"
      galaxy_email_username: "{{ lookup('env', 'GALAXY_EMAIL_USERNAME') }}"
      galaxy_email_password: "{{ lookup('env', 'GALAXY_EMAIL_PASSWORD' )}}"
      galaxy_rabbit_password: "{{ lookup('env', 'GALAXY_RABBIT_PASSWORD' )}}"
      galaxy_es_host : "{{ lookup('env', 'GALAXY_ES_HOST' )}}"
  roles:
  - { role: galaxy_packages }
  - { role: galaxy_deploy }
