---

- name: Deploy Web Servers
  hosts: web
  sudo: yes
  vars:
      - galaxy_database_local: no
      - galaxy_deploy_web: yes
      - galaxy_deploy_celery: no
  vars_files:
      - galaxy-vault.yml
  roles:
      - { role: galaxy_packages }
      - { role: galaxy_deploy }

- name: Deploy Celery
  hosts: db
  sudo: yes
  vars:
      - galaxy_database_local: yes
      - galaxy_deploy_web: no 
      - galaxy_deploy_celery: yes 
  vars_files:
      - galaxy-vault.yml
  roles:
      - { role: galaxy_packages }
      - { role: galaxy_deploy }

- name: Rebuild Search Indexes
  hosts: es_rebuild_host
  sudo: yes
  tasks:
      - shell: "echo 'y' | galaxy-manage rebuild_index"

- name: Rebuild custom search indexes
  hosts: es_rebuild_host
  sudo: yes
  tasks:
      - shell: "galaxy-manage rebuild_galaxy_indexes"

- name: Notify slack
  hosts: 127.0.0.1 
  connection: local
  roles:
      - { role: notify_slack, notify_slack_message: "{{ galaxy_slack_message }}", when: galaxy_slack_message is defined }
