---

- name: Deploy Web Servers
  hosts: web
  sudo: yes
  vars_files:
    - galaxy-vault.yml
  roles:
  - { role: galaxy_packages }
  - { role: galaxy_deploy , tags: ["all", "web"] }
  # - { role: notify_slack, notify_slack_message: "{{ galaxy_slack_message }}", when: galaxy_slack_message is defined }

- name: Deploy Celery
  hosts: celery
  sudo: yes
  vars_files:
    - galaxy-vault.yml
  roles:
  - { role: galaxy_packages }
  - { role: galaxy_deploy , tags: ["all", "celery"] }

- name: Rebuild Search Indexes
  hosts: es_rebuild_host
  tasks:
    - shell: "echo 'y' | galaxy-manage rebuild_index"

- name: Rebuild custom search indexes
  hosts: es_rebuild_host
  tasks:
    - shell: "galaxy-manage rebuild_galaxy_indexes"
