---
- name: Provision Task Server
  hosts: celery
  # become: yes
  vars:
      galaxy_install_dev_tools: False
      galaxy_install_selinux: "{{ selinux | default(False) }}"
      galaxy_env: PROD
      galaxy_log_dir: '/var/log/galaxy'
  roles:
      - { role: galaxy_packages }
      - { role: auth_users } 
      - { role: auth_keys }
      - { role: selinux, when: galaxy_install_selinux }
      - { role: ntp }
      - { role: supervisorctl, sup_init_name: "supervisord", sup_conf_location: "/etc/supervisord.conf" }
      - { role: iptables_config, galaxy_host_type: 'celery' }
      - { role: machine_init }
