---
- name: Provision Web Server
  hosts: web
  sudo: yes
  vars:
      galaxy_install_dev_tools: False
      galaxy_install_selinux: False
      galaxy_env: PROD
      galaxy_log_dir: '/var/log/galaxy'
  roles:
      - { role: galaxy_packages }
      - { role: auth_users }
      - { role: auth_keys }
      - { role: selinux, when: galaxy_install_selinux }
      - { role: ntp }
      - { role: iptables_config, galaxy_host_type: 'web' }
      - { role: fail2ban }
      - { role: memcached }
      - { role: machine_init }
