---

- name: Restart Celery
  hosts: celery 
  become: yes
  tasks:
    - service: name=supervisord state=restarted

- name: Refresh role count
  hosts: celery 
  become: yes
  tasks:  
    - name: Start the refresh        
      shell: galaxy-manage refresh_role_counts
      register: out
      when: celery_beats
    - debug: var=out.stdout_lines

- name: Rebuild Indexes
  hosts: web
  become: yes
  tasks:  
    - name: Rebuild Custom Indexes
      shell: galaxy-manage rebuild_galaxy_indexes
      when: es_rebuild_host
    - name: Rebuild Index
      shell: galaxy-manage rebuild_index --noinput
      when: es_rebuild_host

- name: Notify slack
  hosts: 127.0.0.1 
  connection: local
  vars:
      slack_message: "{{ galaxy_slack_message | default('None') }}"
  roles:
      - { role: notify_slack,
          notify_slack_message: "{{ slack_message }}",
          when: slack_message != 'None' }
