---

- name: Refresh role count
  hosts: db
  sudo: yes
  tasks:  
    - name: Start the refresh        
      shell: galaxy-manage refresh_role_counts
      register: out
      when: postgres_master
    - debug: var=out.stdout_lines
    - service: name=supervisord state=restarted

- name: Rebuild Indexes
  hosts: web
  sudo: yes
  tasks:  
    - name: Rebuild Custom Indexes
      shell: galaxy-manage rebuild_galaxy_indexes
      when: es_rebuild_host
    - name: Rebuild Index
      shell: galaxy-manage rebuild_index --noinput
      when: es_rebuild_host

- name: Notify slack
  hosts: 127.0.0.1 
  connection: local
  roles:
      - { role: notify_slack, notify_slack_message: "{{ galaxy_slack_message }}", when: galaxy_slack_message is defined }
